name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18'
      - name: Install dependencies
        run: yarn --ignore-engines
      - name: Install Playwright
        run: npx playwright install chromium
      - name: Build project
        run: yarn build
      - name: Run tests
        run: yarn test:reporter
